aa: rand-m9-mstd0.5-inc1
amp: false
batch_size: 32
clip_grad: null
color_jitter: 0.4
cooldown_epochs: 5
crop_pct: null
cutmix: 0.0
data: dataset/tomato_leaf_dataset
decay_rate: 0.1
drop: 0.0
drop_path: 0.1
epochs: 50
eval_checkpoint: ''
eval_metric: top1
hflip: 0.5
img_size: 224
initial_checkpoint: ''
interpolation: ''
local_rank: 0
log_interval: 50
lr: 0.0001
mean: null
min_lr: 1.0e-05
mixup: 0.0
model: models/cswin_tiny_224.pth
momentum: 0.9
no_aug: false
no_prefetcher: false
no_resume_opt: false
num_classes: 11
num_gpu: 1
opt: adamw
opt_eps: null
output: ./output_tomato
pin_mem: false
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
resume: ''
scale:
- 0.08
- 1.0
sched: cosine
seed: 42
smoothing: 0.1
start_epoch: null
std: null
validation_batch_size_multiplier: 1
warmup_epochs: 5
warmup_lr: 1.0e-06
weight_decay: 0.05
workers: 4
