batch_size: 32
data_dir: dataset/tomato_leaf_dataset
epochs: 100
experiment: ''
img_size: 224
log_interval: 50
lr: 0.0001
min_lr: 1.0e-06
model: cct_7_7x2_224
num_classes: 11
opt: adamw
output: outputs_dataset/cct
patience: 10
pin_mem: false
resume: ''
sched: cosine
seed: 42
smoothing: 0.1
warmup_epochs: 5
weight_decay: 0.05
workers: 4
